package com.google.appinventor.components.runtime;

import com.google.appinventor.components.annotations.SimpleObject;

@SimpleObject
public interface Component {
    public static final int ACCELEROMETER_SENSITIVITY_MODERATE = 2;
    public static final int ACCELEROMETER_SENSITIVITY_STRONG = 3;
    public static final int ACCELEROMETER_SENSITIVITY_WEAK = 1;
    public static final int ALIGNMENT_CENTER = 1;
    public static final int ALIGNMENT_NORMAL = 0;
    public static final int ALIGNMENT_OPPOSITE = 2;
    public static final String ASSET_DIRECTORY = "component";
    public static final int BUTTON_SHAPE_DEFAULT = 0;
    public static final int BUTTON_SHAPE_OVAL = 3;
    public static final int BUTTON_SHAPE_RECT = 2;
    public static final int BUTTON_SHAPE_ROUNDED = 1;
    public static final int COLOR_BLACK = -16777216;
    public static final int COLOR_BLUE = -14575885;
    public static final int COLOR_CYAN = -16728876;
    public static final int COLOR_DARK_GREEN = -16738680;
    public static final int COLOR_DEFAULT = 0;
    public static final int COLOR_DKGRAY = -12303292;
    public static final int COLOR_GRAY = -6381922;
    public static final int COLOR_GREEN = -11751600;
    public static final int COLOR_LIGHT_GREEN = -7617718;
    public static final int COLOR_LTGRAY = -3355444;
    public static final int COLOR_MAGENTA = -65281;
    public static final int COLOR_NONE = 16777215;
    public static final int COLOR_ORANGE = -26624;
    public static final int COLOR_PINK = -1499549;
    public static final int COLOR_RED = -769226;
    public static final int COLOR_WHITE = -1;
    public static final int COLOR_YELLOW = -5317;
    public static final String DEFAULT_VALUE_COLOR_BLACK = "&HFF000000";
    public static final String DEFAULT_VALUE_COLOR_BLUE = "&HFF2196F3";
    public static final String DEFAULT_VALUE_COLOR_CYAN = "&HFF00BCD4";
    public static final String DEFAULT_VALUE_COLOR_DEFAULT = "&H00000000";
    public static final String DEFAULT_VALUE_COLOR_DKGRAY = "&HFF444444";
    public static final String DEFAULT_VALUE_COLOR_GRAY = "&HFF9E9E9E";
    public static final String DEFAULT_VALUE_COLOR_GREEN = "&HFF4CAF50";
    public static final String DEFAULT_VALUE_COLOR_LTGRAY = "&HFFCCCCCC";
    public static final String DEFAULT_VALUE_COLOR_MAGENTA = "&HFFFF00FF";
    public static final String DEFAULT_VALUE_COLOR_MATERIALCOLOR_LIGHT_GREEN = "&HFF82CCC4";
    public static final String DEFAULT_VALUE_COLOR_NONE = "&H00FFFFFF";
    public static final String DEFAULT_VALUE_COLOR_ORANGE = "&HFFFF9800";
    public static final String DEFAULT_VALUE_COLOR_PINK = "&HFFE91E63";
    public static final String DEFAULT_VALUE_COLOR_RED = "&HFFF44336";
    public static final String DEFAULT_VALUE_COLOR_WHITE = "&HFFFFFFFF";
    public static final String DEFAULT_VALUE_COLOR_YELLOW = "&HFFFFEB3B";
    public static final String DEFAULT_VALUE_TEXT_TO_SPEECH_COUNTRY = "";
    public static final String DEFAULT_VALUE_TEXT_TO_SPEECH_LANGUAGE = "";
    public static final int DIRECTION_EAST = 3;
    public static final int DIRECTION_MAX = 4;
    public static final int DIRECTION_MIN = -4;
    public static final int DIRECTION_NONE = 0;
    public static final int DIRECTION_NORTH = 1;
    public static final int DIRECTION_NORTHEAST = 2;
    public static final int DIRECTION_NORTHWEST = -4;
    public static final int DIRECTION_SOUTH = -1;
    public static final int DIRECTION_SOUTHEAST = 4;
    public static final int DIRECTION_SOUTHWEST = -2;
    public static final int DIRECTION_WEST = -3;
    public static final int FAB_ANIMATION_DURATION_DEFAULT = 300;
    public static final int FAB_ELEVATION_DEFAULT = 6;
    public static final int FAB_ICON_SIZE_DEFAULT = 24;
    public static final int FAB_PADDINGBOTTOM_DEFAULT = 16;
    public static final int FAB_PADDINGRIGHT_DEFAULT = 16;
    public static final int FAB_SIZE_DEFAULT = 56;
    public static final int FAB_SIZE_MINI = 40;
    public static final float FONT_DEFAULT_SIZE = 14.0f;
    public static final String ICON_NAME_PLUS = "add";
    public static final int LAYOUT_ORIENTATION_HORIZONTAL = 0;
    public static final int LAYOUT_ORIENTATION_VERTICAL = 1;
    public static final int LENGTH_FILL_PARENT = -2;
    public static final int LENGTH_PERCENT_TAG = -1000;
    public static final int LENGTH_PREFERRED = -1;
    public static final int LENGTH_UNKNOWN = -3;
    public static final int MATERIALCOLOR_LIGHT_GREEN = -8205116;
    public static final int SCALING_SCALE_PROPORTIONALLY = 0;
    public static final int SCALING_SCALE_TO_FIT = 1;
    public static final float SLIDER_MAX_VALUE = 50.0f;
    public static final float SLIDER_MIN_VALUE = 10.0f;
    public static final float SLIDER_THUMB_VALUE = 30.0f;
    public static final int TOAST_LENGTH_LONG = 1;
    public static final int TOAST_LENGTH_SHORT = 0;
    public static final int TYPEFACE_DEFAULT = 0;
    public static final int TYPEFACE_MONOSPACE = 3;
    public static final int TYPEFACE_ROBOTOREGULAR = 4;
    public static final int TYPEFACE_ROBOTOTHIN = 5;
    public static final int TYPEFACE_SANSSERIF = 1;
    public static final int TYPEFACE_SERIF = 2;

    HandlesEventDispatching getDispatchDelegate();
}
